
export const rows = [
    {
      id: 1,
      name: "Ahmed Azmy",
      email: "ahmedazmy@gmail.com",
      age: 25,
      phone: "01234567802",
      cost: "4,000.00 $",
      address: "094 WOn BNS",
      city: "Cairo",
      zipCode: "12345",
      regestarId: "123512",
    },
    {
      id: 2,
      name: "Aya Taha",
      email: "ayat@gmail.com",
      age: 22,
      phone: "0123456789",
      cost: "2,500.00 $",
      address: "123 Elm Street",
      city: "Alexandria",
      zipCode: "21523",
      regestarId: "984521",
    },
    {
      id: 3,
      name: "Hassan Omar",
      email: "hassan.omar@gmail.com",
      age: 30,
      phone: "0112233445",
      cost: "2,000.00 $",
      address: "456 Pine Avenue",
      city: "Giza",
      zipCode: "11231",
      regestarId: "785214",
    },
    {
      id: 4,
      name: "Mona Ali",
      email: "mona.ali@yahoo.com",
      age: 28,
      phone: "0156677889",
      cost: "2,200.00 $",
      address: "789 Maple Road",
      city: "Mansoura",
      zipCode: "35516",
      regestarId: "635712",
    },
    {
      id: 5,
      name: "Youssef Tarek",
      email: "youssef.tarek@hotmail.com",
      age: 21,
      phone: "0109988776",
      cost: "1,950.00 $",
      address: "321 Cedar Lane",
      city: "Aswan",
      zipCode: "81111",
      regestarId: "251478",
    },
    {
      id: 6,
      name: "Amira Khaled",
      email: "amira.khaled@gmail.com",
      age: 27,
      phone: "0145632189",
      cost: "1,800.00 $",
      address: "654 Oak Street",
      city: "Luxor",
      zipCode: "75849",
      regestarId: "785946",
    },
    {
      id: 7,
      name: "Karim Hassan",
      email: "karim.hassan@gmail.com",
      age: 35,
      phone: "0162233445",
      cost: "1,580.00 $",
      address: "987 Walnut Avenue",
      city: "Hurghada",
      zipCode: "45621",
      regestarId: "412569",
    },
    {
      id: 8,
      name: "Laila Sameh",
      email: "laila.sameh@yahoo.com",
      age: 24,
      phone: "0135648971",
      cost: "1,550.00 $",
      address: "135 Birch Lane",
      city: "Sharm El-Sheikh",
      zipCode: "86914",
      regestarId: "378541",
    },
    {
      id: 9,
      name: "Omar Farouk",
      email: "omar.farouk@hotmail.com",
      age: 32,
      phone: "0178899001",
      cost: "1,500.00 $",
      address: "246 Palm Road",
      city: "Port Said",
      zipCode: "12345",
      regestarId: "695874",
    },
    {
      id: 10,
      name: "Nour Hany",
      email: "nour.hany@gmail.com",
      age: 29,
      phone: "0187654321",
      cost: "1,200.00 $",
      address: "369 Chestnut Street",
      city: "Zagazig",
      zipCode: "67812",
      regestarId: "851429",
    },
    {
      id: 11,
      name: "Tamer Adel",
      email: "tamer.adel@gmail.com",
      age: 26,
      phone: "0198765432",
      cost: "1,000.00 $",
      address: "852 Sycamore Lane",
      city: "Ismailia",
      zipCode: "96321",
      regestarId: "147852",
    },
  ];
  
  
  export const columns = [
    {
      field: "id",
      headerName: "ID",
      align: "center",
      headerAlign: "center",
      // width:33,
      // flex:1 
    },
    {
      field: "regestarId",
      headerName: "Registar ID",
      align: "center",
      headerAlign: "center",
    },
    {
      field: "name",
      headerName: "Name",
      align: "center",
      headerAlign: "center",
      // flex: 1,
      // cellClassName: "name-column--cell",
    },
    {
      field: "age",
      headerName: "Age",
      type: "number",
      align: "center",
      headerAlign: "center",
    },
    {
        field: "cost",
        headerName: "Cost",
        type: "number",
        align: "center",
        headerAlign: "center",
      },
    {
      field: "phone",
      headerName: "Phone Number",
      align: "center",
      headerAlign: "center",
      flex: 1,
    },
    {
      field: "email",
      headerName: "Email",
      align: "center",
      headerAlign: "center",
      flex: 1,
    },
    {
      field: "address",
      headerName: "Address",
      align: "center",
      headerAlign: "center",
      // flex: 1,
    },
    {
      field: "city",
      headerName: "City",
      flex: 1,
      align: "center",
      headerAlign: "center",
    },
    {
      field: "zipCode",
      headerName: "Zip Code",
      align: "center",
      headerAlign: "center",
    },
  ];